apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  project: observability
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 9.0.0
    chart: grafana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
